# Default values for handbrake-watcher.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: chrisjohnson00/handbrake-job-creator
  pullPolicy: IfNotPresent
  tag: v1.0.0

nameOverride: "handbrake-job-creator"
fullnameOverride: "handbrake-job-creator"
localPath: /nfs-data
# the full path for watch becomes {{localPath}}/{{watchPath}}_{{quality}}
watchPath: watch
quality: 720p
movePath: encoding_queue
encodingProfile: "Roku 720p30 Surround"
jobType: tv

serviceAccount:
  name: "handbrake-job-creator-svc-acnt"
  annotations: []

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  limits:
    cpu: 250m
    memory: 400Mi
  requests:
    cpu: 50m
    memory: 200Mi

nodeSelector: {}

tolerations: []

affinity: {}
