# Default values for handbrake-watcher.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: chrisjohnson00/handbrake-job-creator
  pullPolicy: IfNotPresent
  tag: v1.0.0

nameOverride: "handbrake-job-creator"
fullnameOverride: "handbrake-job-creator"
watchPath: /override/this
quality: 720p
movePath: /data/k8s/encoding_queue
encodingProfile: "Roku 720p30 Surround"
jobType: tv
# the needle is what to look for, value is what to replace with
# for example if the watcher creates jobs to downgrade resolution, you might want to set
# needle to 1080p and value to 720p so that any 1080p file (with 1080p in the name) encoded comes out with 720p in the
# name instead
fileNameReplaceNeedle: None
fileNameReplaceValue: None
consulHttpAddr: "consul-consul-server.consul:8500"

volumeMounts:
  watch:
    mountPath: /watch
  move:
    mountPath: /move

serviceAccount:
  name: "handbrake-job-creator-svc-acnt"
  annotations: []

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  limits:
    cpu: 250m
    memory: 400Mi
  requests:
    cpu: 50m
    memory: 200Mi

nodeSelector: {}

tolerations: []

affinity: {}

labels: {}

annotations: {}

nfs:
  server: 192.168.10.131
