apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.serviceAccount.name }}-rb-{{ .Values.nameOverride }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}-{{ .Values.nameOverride }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.serviceAccount.name }}-cr-{{ .Values.nameOverride }}
  apiGroup: rbac.authorization.k8s.io