apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "handbrake-watcher.fullname" . }}
  labels:
    {{- include "handbrake-watcher.labels" . | nindent 4 }}
    {{- if .Values.labels -}}
    {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  serviceName: {{ .Values.nameOverride }}
  selector:
    matchLabels:
      {{- include "handbrake-watcher.selectorLabels" . | nindent 6 }}
      {{- if .Values.labels -}}
      {{- toYaml .Values.labels | nindent 6 }}
      {{- end }}
  template:
    metadata:
      labels:
        {{- include "handbrake-watcher.selectorLabels" . | nindent 8 }}
        {{- if .Values.labels -}}
        {{- toYaml .Values.labels | nindent 8 }}
        {{- end }}
      annotations:
        {{- toYaml .Values.annotations | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}-{{ .Values.nameOverride }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: JOB_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: JOB_PROFILE
              value: {{ .Values.encodingProfile }}
            - name: QUALITY
              value: {{ .Values.quality }}
            - name: CONSUL_HTTP_ADDR
              value: consul-consul-server.consul:8500
            - name: JOB_TYPE
              value: {{ .Values.jobType }}
            - name: FILE_NAME_REPLACE_NEEDLE
              value: {{ .Values.fileNameReplaceNeedle }}
            - name: FILE_NAME_REPLACE_VALUE
              value: {{ .Values.fileNameReplaceValue }}
          volumeMounts:
            - name: watch
              mountPath: /watch
            - name: move
              mountPath: /move
      volumes:
        - name: watch
          nfs:
            server: "{{ .Values.nfs.server }}"
            path: "{{ .Values.watchPath }}"
        - name: move
          nfs:
            server: "{{ .Values.nfs.server }}"
            path: "{{ .Values.movePath }}"
